#10 добавить схему БД
EvgeniPolyakov/java-filmorate pull request #5
Opened 2022-07-03 10:31 UTC by EvgeniPolyakov

2022-07-03 10:45 UTC, ArsenyIshtubaev approved these changes

2022-07-11 20:26 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/MPAController.java
> +public class MPAController {
сокращения в названиях классов тоже должны быть в CamelCase:
`MpaController`

2022-07-11 20:33 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            genreStorage.assignGenreToFilm(filmId, genres);
можно было сделать этот метод в этом репозитории, тогда не нужно было бы добавлять в зависимости другое хранилище
но это на усмотрение студента)

2022-07-11 20:34 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +        Long id = rs.getLong("GENRE_ID");
названия колонок и название таблицы можно вынести в константы
запросы выносить не нужно

2022-07-11 21:02 UTC, makholin commented on src/test/java/ru/yandex/practicum/filmorate/service/FilmServiceTest.java
> +    @Transactional
транзакций не должно быть в тестовых методах
они должны быть указаны на методах стораджа, или вообще коммиты должны делаться вручную у jdbc template
об этом подробнее можно в инете прочитать или у куратора спросить

2022-07-11 21:04 UTC, makholin requested changes
Нужно исправить замечания

2022-07-12 08:08 UTC, EvgeniPolyakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            genreStorage.assignGenreToFilm(filmId, genres);
Изначально так и планировалось, но эта зависмость всё равно требуется затем ниже для маппера. Потому так и оставил. Не вижу более изящного решения.

2022-07-12 08:14 UTC, EvgeniPolyakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +        Long id = rs.getLong("GENRE_ID");
Позволю себе здесь также оставить всё, как есть, так как:
- это лишь разово встречающиеся две позиции
- это все же не "магические числа", а вполне информативные стринги
- в результате рефакторинга ради двух стрингов размером в 5 и 8 символов будут добавлены две строчки кода с, по сути, тем же текстом

Скажи, если я что-то неверно понимаю и нормы чистого кода всё равно требуют такое выносить в константы.

2022-07-12 18:20 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +        Long id = rs.getLong("GENRE_ID");
константы  не призваны укорачивать код и могут использоваться не только когда много одинаковых значений

тут выражение 
`Long id = rs.getLong(GENRE_ID_FIELD)`
было бы чуть более понятно, чем 
`Long id = rs.getLong("GENRE_ID")`
потому что у константы есть ее имя и значение, а у переданной в аргумент строки  есть только значение, по которому нужно понять смысл 

это можно оставить на усмотрение студента

2022-07-12 18:23 UTC, makholin approved these changes
Работа принята

2022-07-13 09:04 UTC, merged